### ISSUE TITLE
Getting exception java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by tushargoel86** [eugenp/tutorials#10063]
Getting exception when callig PriorityBlockingQueue Example as per article https://www.baeldung.com/java-priority-job-schedule
'
Exception in thread "pool-2-thread-1" java.util.concurrent.RejectedExecutionException: Task scheduler.Job@1789e283 rejected from java.util.concurrent.ThreadPoolExecutor@194e1e02[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at scheduler.PriorityJobSchedular.lambda$1(PriorityJobSchedular.java:27)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by tushargoel86** [comment]
I figured it out. I was calling shutdown immediately after adding a job. I have added sleep time after the job addition and before calling shutdown.
