### ISSUE TITLE
Error build spring-boot-mvc-birt

### ISSUE THREAD

**Issue by alexisaraya** [eugenp/tutorials#10116]
Error build spring-boot-mvc-birt

i tried build and running  
>`mvn spring-boot:run`

`SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/u1309090/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.13.3/log4j-slf4j-impl-2.13.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/u1309090/.m2/repository/com/innoventsolutions/birt/runtime/org.eclipse.birt.runtime_4.8.0-20180626/4.8.0/org.eclipse.birt.runtime_4.8.0-20180626-4.8.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/u1309090/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.baeldung.birt.engine.ReportEngineApplication.main(ReportEngineApplication.java:19)
Caused by: org.apache.logging.log4j.LoggingException: log4j-slf4j-impl cannot be present with log4j-to-slf4j
        at org.apache.logging.slf4j.Log4jLoggerFactory.validateContext(Log4jLoggerFactory.java:49)
        at org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:39)
        at org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:30)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:54)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:242)
        at org.apache.commons.logging.LogAdapter$Slf4jAdapter.createLocationAwareLog(LogAdapter.java:130)
        at org.apache.commons.logging.LogAdapter.createLog(LogAdapter.java:91)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:67)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:59)
        at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:196)
        ... 1 more`

**Comment by rajputvishwas** [comment]
Hi @alexisaraya,
Which spring boot version are you using?

**Comment by lor6** [comment]
Hi @alexisaraya I've added a fix for this issue. Please update your local repository and try again.

Thanks.
