### ISSUE TITLE
Testcontainers with PostgreSQLExtension: Unable to acquire JDBC Connection

### ISSUE THREAD

**Issue by bteo618** [eugenp/tutorials#11011]
Hi,
https://www.baeldung.com/spring-dynamicpropertysource

On chapter 5, it was suggested to use @ExtendWith(PostgreSQLExtension.class), the idea is good.
But, it will hit the following error while running the test if **more than one test classes** are annotated. Any idea? Thanks.

```2021-07-08 19:14:47.441  WARN 8284 --- [    Test worker] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Failed to validate connection org.postgresql.jdbc.PgConnection@3395eade (This connection has been closed.). Possibly consider using a shorter maxLifetime value.
2021-07-08 19:14:47.445  WARN 8284 --- [    Test worker] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Failed to validate connection org.postgresql.jdbc.PgConnection@41f51019 (This connection has been closed.). Possibly consider using a shorter maxLifetime value.
2021-07-08 19:14:47.447  WARN 8284 --- [    Test worker] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Failed to validate connection org.postgresql.jdbc.PgConnection@5daac1e3 (This connection has been closed.). Possibly consider using a shorter maxLifetime value.
2021-07-08 19:14:47.449  WARN 8284 --- [    Test worker] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Failed to validate connection org.postgresql.jdbc.PgConnection@306bf242 (This connection has been closed.). Possibly consider using a shorter maxLifetime value.
2021-07-08 19:14:47.450  WARN 8284 --- [    Test worker] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Failed to validate connection org.postgresql.jdbc.PgConnection@21a35c67 (This connection has been closed.). Possibly consider using a shorter maxLifetime value.
2021-07-08 19:14:47.451  WARN 8284 --- [    Test worker] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Failed to validate connection org.postgresql.jdbc.PgConnection@483ff592 (This connection has been closed.). Possibly consider using a shorter maxLifetime value.
2021-07-08 19:14:47.452  WARN 8284 --- [    Test worker] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Failed to validate connection org.postgresql.jdbc.PgConnection@431190af (This connection has been closed.). Possibly consider using a shorter maxLifetime value.
2021-07-08 19:14:47.453  WARN 8284 --- [    Test worker] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Failed to validate connection org.postgresql.jdbc.PgConnection@2c07836d (This connection has been closed.). Possibly consider using a shorter maxLifetime value.
2021-07-08 19:14:47.454  WARN 8284 --- [    Test worker] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Failed to validate connection org.postgresql.jdbc.PgConnection@177cb2ee (This connection has been closed.). Possibly consider using a shorter maxLifetime value.
2021-07-08 19:14:47.455  WARN 8284 --- [    Test worker] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Failed to validate connection org.postgresql.jdbc.PgConnection@20d856f6 (This connection has been closed.). Possibly consider using a shorter maxLifetime value.
2021-07-08 19:15:17.438  WARN 8284 --- [    Test worker] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 08001
2021-07-08 19:15:17.438 ERROR 8284 --- [    Test worker] o.h.engine.jdbc.spi.SqlExceptionHelper   : HikariPool-1 - Connection is not available, request timed out after 30001ms.
2021-07-08 19:15:17.439 ERROR 8284 --- [    Test worker] o.h.engine.jdbc.spi.SqlExceptionHelper   : Connection to localhost:55243 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:467)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:595)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:382)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
```

**Comment by kwoyke** [comment]
Hi @bteo618 ,

Thanks for the feedback.
We've updated our code and the article.

Cheers

**Comment by MikhailShumenko** [comment]
And what did you update?
