### ISSUE TITLE
com.baeldung.boot.embeddedRedis.domain.repository.UserRepositoryIntegrationTest#shouldSaveUser_toRedis failed: Can't start redis server

### ISSUE THREAD

**Issue by igilbert** [eugenp/tutorials#12396]
Executed On Windows OS, encoutering the error
`
Caused by: java.lang.RuntimeException: Can't start redis server. Check logs for details.
	at redis.embedded.AbstractRedisInstance.awaitRedisServerReady(AbstractRedisInstance.java:62)
	at redis.embedded.AbstractRedisInstance.start(AbstractRedisInstance.java:39)
	at redis.embedded.RedisServer.start(RedisServer.java:9)
	at com.baeldung.boot.embeddedRedis.TestRedisConfiguration.postConstruct(TestRedisConfiguration.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)`

setting mem workarounds it.
`  public TestRedisConfiguration(final RedisProperties redisProperties) {
        this.redisServer = RedisServer.builder().port(redisProperties.getPort()).setting("maxmemory 128M").build();
//        this.redisServer = new RedisServer(redisProperties.getPort());
    }`

**Comment by dkapil** [comment]
This is now resolved, please have a look on the test on how to run this on windows
