### ISSUE TITLE
MiniKDC exception in thread "main"

### ISSUE THREAD

**Issue by lorenzobruno7** [eugenp/tutorials#14399]
Hi, when i try to run KerberosMiniKdc.java, this error occours

`Exception in thread "main" java.lang.IllegalAccessException: class org.springframework.security.kerberos.test.MiniKdc cannot access class 
sun.security.krb5.Config (in module java.security.jgss) because module java.security.jgss does not export sun.security.krb5 to unnamed module @740d2e78
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
        at java.base/java.lang.reflect.Method.invoke(Method.java:560)
        at org.springframework.security.kerberos.test.MiniKdc.initKDCServer(MiniKdc.java:457)
        at org.springframework.security.kerberos.test.MiniKdc.start(MiniKdc.java:306)
        at org.springframework.security.kerberos.test.MiniKdc.main(MiniKdc.java:139)
        at kerberos.kdc.KerberosMiniKdc.main(KerberosMiniKdc.java:24)`

How can i fix it?

**Comment by ulisseslima** [comment]
Hey, @lorenzobruno7.

You can run [this project](https://github.com/eugenp/tutorials/blob/master/spring-security-modules/spring-security-oauth2-sso/spring-security-sso-kerberos/pom.xml) with Java 8, so this error won't happen.

We have internal tasks to keep projects updated with the latest Java version, but it might take a while.

https://www.baeldung.com/spring-security-kerberos-integration

**Comment by dkapil** [comment]
If we are working with JDK 9 or later, we need to enable the java.security.jgss [module](https://staging43.baeldung.com/java-9-modularity) in our IDEs in order to start the MiniKdc successfully. We can do this through a command line parameter that we can set during the execution of the Main class:

`--add-exports java.security.jgss/sun.security.krb5=ALL-UNNAMED`
