### ISSUE TITLE
You need to run build with JDK or have tools.jar on the classpath  - Full Rest Example

### ISSUE THREAD

**Issue by pashtika** [eugenp/tutorials#247]
Hello,

I see following error coming in pom when project is imported to STS. I'm using Java 8, and my Java-->Installed JRE pointing to Jdk1.8.0.45. Any guidance?

"You need to run build with JDK or have tools.jar on the classpath.If this occures during eclipse build make sure you 
 run eclipse under JDK as well (com.mysema.maven:apt-maven-plugin:1.1.3:process:default:generate-sources)"

**Comment by eugenp** [comment]
Yes - it's unfortunately an Eclipse issue - because you're pointing Eclipse to the JDK - which is good, but Eclipse itself is a Java app that also runs in a JVM. And it's running in the JRE instead of the JDK. 
The way to fix that is - in your `eclipse.ini` (or `STS.ini` - if you're using Eclipse STS) - you add this first line: 
```
-vm 
C:\Java\jdk1.8.0_60\bin\javaw.exe
```
If you're on Windows that is. If you're on Linux or on the Mac - you'll basically have to use the right path there. 
Hope it helps. Cheers, 
Eugen.

**Comment by pashtika** [comment]
You're great. Many thanks for all your suggestions.

**Comment by eugenp** [comment]
Happy to help. Closing this one.

**Comment by ffahim** [comment]
Thanks

**Comment by gilbelan** [comment]
Very good!!!

**Comment by vherasme** [comment]
Hi. I am facing the same issue. This is a part of the console log:

```
[ERROR] execute error
org.apache.maven.plugin.MojoExecutionException: You need to run build with JDK or have tools.jar on the classpath.If this occures during eclipse build make sure you run eclipse under JDK as well
	at com.mysema.maven.apt.AbstractProcessorMojo.execute(AbstractProcessorMojo.java:310)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
```

**Comment by eugenp** [comment]
Hey @vherasme - so does that mean that the solution earlier in this thread didn't work?

**Comment by vherasme** [comment]
@eugenp After many tries it worked. Right now I cannot tell you what the final solution looked like. But I think it had something to do with having a **JRE INSTEAD OF A JDK**

**Comment by murali1220** [comment]
I too got the same exception even after adding STS.ini I was getting the same exception. I resolved by removing jre library from build path and added tools.jar.

**Comment by eugenp** [comment]
There are a few known issues focused on the best way to run Eclipse, and how to handle multiple installations of the JRE and JDK out there. I think the best way to go here is to find and use those - no point in duplicating those discussions here.

**Comment by reddykanth088** [comment]
You need to run build with JDK or have tools.jar on the classpath.If this occures during eclipse build make sure you run eclipse under JDK as well (com.mysema.maven:apt-maven-plugin:1.1.3:process:default:generate-sources)

org.apache.maven.plugin.MojoExecutionException: You need to run build with JDK or have tools.jar on the classpath.If this occures during eclipse build make sure you run eclipse under JDK as well
	at com.mysema.maven.apt.AbstractProcessorMojo.execute(AbstractProcessorMojo.java:362)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
	at

**Comment by hariprasad108** [comment]
Hello Eugen, I think, that it is not quite correct. I must use different path. For example:
-vm 
c:\Java\jdk1.8.0_181\jre\bin\javaw.exe
I.e. JRE inside of JDK installation. Otherwise Eclipse won't start.
The version of Java should be same as in parameter 'requiredJavaVersion' in eclipse.ini.

**Comment by poyrazus** [comment]
I also had the same problem today. What I did:

- Uninstalled Java and installed it to a path without a space (C:\Java\jdk1.8.0_191)
- Set eclipse to use this JDK instead of a jre
- Changed the -vm parameter in eclipse.ini as told above. The important thing is, it must come before -vmargs parameter.
- Restart eclipse.
- Right click the project in eclipse, maven->update

**Comment by Chekoares75** [comment]
> Yes - it's unfortunately an Eclipse issue - because you're pointing Eclipse to the JDK - which is good, but Eclipse itself is a Java app that also runs in a JVM. And it's running in the JRE instead of the JDK.
> The way to fix that is - in your `eclipse.ini` (or `STS.ini` - if you're using Eclipse STS) - you add this first line:
> 
> ```
> -vm 
> C:\Java\jdk1.8.0_60\bin\javaw.exe
> ```
> If you're on Windows that is. If you're on Linux or on the Mac - you'll basically have to use the right path there.
> Hope it helps. Cheers,
> Eugen.

Thanks a lot! It works for me.

**Comment by dsaro** [comment]
Hi guys!
thanks a lot!

-vm 
C:\Java\jdk1.8.0_60\bin\javaw.exe

it helped me to fix it
 for setting of my spring roo project in STS (needed for some Comp. work)

I added above two lines as first lines into sts.ini and of course to point to my Java installation path!
Also checked if jdk or jre is set in my IDE as default, 
and also that project's pom.xml points to right java version (for me java 1.8). 
Also did > Maven> Update project
and checked to have right dependencies versions in pom.

Thanks!
Danijela
