### ISSUE TITLE
build and run issue

### ISSUE THREAD

**Issue by mitendraanand** [eugenp/tutorials#2913]
How to build this project using maven?
if I do mvn clean package, I see the jar file got created in target. But how do we run client and server?

**Comment by lor6** [comment]
Hi @mitendraanand. Which project do you mean? The tutorial directory contains many projects that can be run separately.

**Comment by mitendraanand** [comment]
https://github.com/eugenp/tutorials/tree/master/grpc

**Comment by mitendraanand** [comment]
Below command:
java -cp target/grpctest-0.0.1-SNAPSHOT.jar com.xyz.grpc.server.GrpcServer

Gives this error:
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: io/grpc/BindableService
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: io.grpc.BindableService
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

**Comment by mitendraanand** [comment]
probably I am missing gRPC dependencies in JAR file. How to make the JAR file include them?

**Comment by mitendraanand** [comment]
No Worries. Below in POM.xml solved it. Thanks. 

            <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-shade-plugin</artifactId>
            <version>2.4.3</version>
            <executions>
                <execution>
                <phase>package</phase>
                <goals>
                    <goal>shade</goal>
                </goals>
                <configuration>
                    <transformers>
                    <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                        <mainClass>package.Main</mainClass>
                    </transformer>
                    </transformers>
                </configuration>
                </execution>
            </executions>
            </plugin>
