### ISSUE TITLE
i am getting this error in pom.xml

### ISSUE THREAD

**Issue by reddykanth088** [eugenp/tutorials#3025]
You need to run build with JDK or have tools.jar on the classpath.If this occures during eclipse build make sure you run eclipse under JDK as well (com.mysema.maven:apt-maven-plugin:1.1.3:process:default:generate-sources)

org.apache.maven.plugin.MojoExecutionException: You need to run build with JDK or have tools.jar on the classpath.If this occures during eclipse build make sure you run eclipse under JDK as well
	at com.mysema.maven.apt.AbstractProcessorMojo.execute(AbstractProcessorMojo.java:362)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
	at

**Comment by eugenp** [comment]
It looks like your Eclipse is pointing to a JRE instead of a JDK as the default tool you're building with. 
If you change that, it should work fine.
