### ISSUE TITLE
spring-katharsis: doesnt work with the latest version of Katharsis

### ISSUE THREAD

**Issue by ashishgodani** [eugenp/tutorials#327]
This code doesnt work with the latest release of Katharsis - I just changed the version `<katharsis.version>2.1.3</katharsis.version>` and it started throwing:

``` java
org.reflections.ReflectionsException: could not get type for name io.katharsis.dispatcher.controller.resource.ResourceIncludeField
    at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:389)
    at org.reflections.ReflectionUtils.forNames(ReflectionUtils.java:398)
    at org.reflections.Reflections.getSubTypesOf(Reflections.java:357)
    at io.katharsis.dispatcher.registry.ControllerRegistryBuilder.build(ControllerRegistryBuilder.java:46)
    at io.katharsis.invoker.KatharsisInvokerBuilder.createRequestDispatcher(KatharsisInvokerBuilder.java:139)
    at io.katharsis.invoker.KatharsisInvokerBuilder.build(KatharsisInvokerBuilder.java:113)
    at io.katharsis.servlet.AbstractKatharsisFilter.createKatharsisInvoker(AbstractKatharsisFilter.java:149)
    at io.katharsis.servlet.AbstractKatharsisFilter.getKatharsisInvoker(AbstractKatharsisFilter.java:107)
    at io.katharsis.servlet.AbstractKatharsisFilter.doFilter(AbstractKatharsisFilter.java:86)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1526)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1482)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by eugenp** [comment]
Hey @ashishgodani quick update here. We have an internal task to upgrade the code and the article to the latest supported version - should be done in a few weeks. 
Closing this one. Cheers, 
Eugen.
