### ISSUE TITLE
Failed to execute goal on project jackson: Could not r esolve dependencies for project org.baeldung:jackson:jar:1.0: Failed to collect dependencies at com.fasterxml. jackson.core:jackson-databind:jar:2.7.1-1

### ISSUE THREAD

**Issue by JavaNeed** [eugenp/tutorials#379]
This is reg "jackson" project, when I was trying to build compile project using `mvn clean install -DskipTests`, I see following error's are coming. Please help me to resolved this. I'm using STS.

```
4, DefaultDependencyCollector.collectTime=780, DefaultDependencyCollector.transformTime=16}
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.638 s
[INFO] Finished at: 2016-03-06T11:59:32+05:30
[INFO] Final Memory: 10M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jackson: Could not resolve dependencies for project org.baeldung:jac
kson:jar:1.0: Failed to collect dependencies at com.fasterxml.jackson.core:jackson-databind:jar:2.7.1-1: Faile
d to read artifact descriptor for com.fasterxml.jackson.core:jackson-databind:jar:2.7.1-1: Could not transfer
artifact com.fasterxml.jackson.core:jackson-databind:pom:2.7.1-1 from/to central (https://repo.maven.apache.or
g/maven2): repo.maven.apache.org: Unknown host repo.maven.apache.org -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project jackson: Could not r
esolve dependencies for project org.baeldung:jackson:jar:1.0: Failed to collect dependencies at com.fasterxml.
jackson.core:jackson-databind:jar:2.7.1-1
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependency
Resolver.java:220)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(Lifecycl
eDependencyResolver.java:127)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:25
7)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java
:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java
:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThread
edBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project
org.baeldung:jackson:jar:1.0: Failed to collect dependencies at com.fasterxml.jackson.core:jackson-databind:ja
r:2.7.1-1
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResol
ver.java:180)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependency
Resolver.java:195)
        ... 22 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at com.
fasterxml.jackson.core:jackson-databind:jar:2.7.1-1
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCo
llector.java:291)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySyste
m.java:316)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResol
ver.java:172)
        ... 23 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for c
om.fasterxml.jackson.core:jackson-databind:jar:2.7.1-1
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescrip
torReader.java:302)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(Default
ArtifactDescriptorReader.java:217)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(Default
DependencyCollector.java:525)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDepe
```

**Comment by eugenp** [comment]
The dependency should be available from Maven central: http://search.maven.org/#artifactdetails|com.fasterxml.jackson.core|jackson-databind|2.7.1-1|bundle. 
I'm upgrading it and you can try the new one - but again, the one that the project is using should be available.

**Comment by eugenp** [comment]
Cool, I'm closing this thread, but of course, if you have any questions, just ping me here
