### ISSUE TITLE
 java.lang.ClassCastException: com.mongodb.BasicDBObject cannot be cast to com.mongodb.BasicDBList] with root cause java.lang.ClassCastException

### ISSUE THREAD

**Issue by DhyanandraSingh** [eugenp/tutorials#393]
I am using spring data and mongodb. I creating a model containing list of country and their neighbour country and i implemented cascade using generic implementation but i get an error i.e.

```
 java.lang.ClassCastException: com.mongodb.BasicDBObject cannot be cast to com.mongodb.BasicDBList] with root cause
java.lang.ClassCastException: com.mongodb.BasicDBObject cannot be cast to com.mongodb.BasicDBList
    at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeInternal(MappingMongoConverter.java:385)
    at org.springframework.data.mongodb.core.convert.MappingMongoConverter.write(MappingMongoConverter.java:354)
    at org.springframework.data.mongodb.core.convert.MappingMongoConverter.write(MappingMongoConverter.java:78)
    at org.springframework.data.mongodb.core.MongoTemplate.toDbObject(MongoTemplate.java:813)
    at org.springframework.data.mongodb.core.MongoTemplate.doSave(MongoTemplate.java:972)
    at org.springframework.data.mongodb.core.MongoTemplate.save(MongoTemplate.java:921)
    at org.springframework.data.mongodb.core.MongoTemplate.save(MongoTemplate.java:909)
    at com.nxtlife.law.event.CascadeCallback.doWith(CascadeCallback.java:32)
    at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:689)
    at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:669)
    at com.nxtlife.law.event.CascadeSaveMongoEventListener.onBeforeConvert(CascadeSaveMongoEventListener.java:15)
    at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onBeforeConvert(AbstractMongoEventListener.java:119)
    at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:88)
    at org.springframework.data.mongodb.core.mapping.event.AbstractMongoEventListener.onApplicationEvent(AbstractMongoEventListener.java:33)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:381)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:335)
    at org.springframework.data.mongodb.core.MongoTemplate.maybeEmitEvent(MongoTemplate.java:1611)
    at org.springframework.data.mongodb.core.MongoTemplate.doInsert(MongoTemplate.java:793)
    at org.springframework.data.mongodb.core.MongoTemplate.insert(MongoTemplate.java:743)
    at com.nxtlife.law.dao.impl.CountryDaoImpl.addCountry(CountryDaoImpl.java:29)
    at com.nxtlife.law.service.impl.CountryServiceImpl.addCountry(CountryServiceImpl.java:23)
    at com.nxtlife.law.controller.LocationController.saveCountry(LocationController.java:52)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969)
    at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:871)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Unknown Source)

```
## Country.java

```
import java.util.ArrayList;
import java.util.List;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import com.nxtlife.law.annotation.CascadeSave;

@Document(collection = "country")
public class Country {

    @Id
    @Field("country_id")
    private String countryId;

    @Indexed
    @Field("country_name")
    private String countryName;

    @Field("status")
    private boolean status = true;

    @DBRef
    @CascadeSave
    private List<Country> neighbourCountry = new ArrayList<>();
```
## CountryDaoImpl

```

public class CountryDaoImpl implements CountryDao {

    @Autowired
    private MongoTemplate mongoTemplate;

    public static final String COLLECTION_NAME = "country";

    @Override
    public void addCountry(Country country) {

        if (!mongoTemplate.collectionExists(Country.class)) {
            mongoTemplate.createCollection(Country.class);
            }

        country.setCountryId(UUID.randomUUID().toString());
            mongoTemplate.insert(country, COLLECTION_NAME);
    }
}
```

**Comment by eugenp** [comment]
I remember there was a JIRA about this on the Spring MongoDB project - it may be related to the version of MongoDB you're using.  
Also - this is an interesting one for me. My own personal experience with MongoDB is limited. I'll probably have to dig into the problem a lot more that surface level to get to the root cause. 
In these cases, I try to point readers to StackOverflow - you'll likely get a better answer from someone who's been using the library recently. 
I expect that, for articles written by other authors than myself on the site, this may happen from time to time. I try to not restrict new authors to topics that I'm personally experienced in - but this is one of the downsides of that. 
Hope that all makes sense. Cheers, 
Eugen.

**Comment by vickyshah129** [comment]
although it is late. The actual mistake people doing with this tutorial is not changing according to their scenario. Tutorial is using Entity for @DBRef and you are using collection. So in class **CascadeCallback** you have to parse the field in collection and then iterate over it to call getMongoOperations().save(objectInCollection);

Hope that will help for people reading this tutorial now.

**Comment by d3minem** [comment]
@vickyshah129 - I agree with you. For collection, it should be handled inside the **CascadeCallback** but the <if block> never becomes true and the code never execute it. 

      if (field.isAnnotationPresent(DBRef.class) && field.isAnnotationPresent(CascadeSave.class)) 

Do I need to write the `Converter` as well? just like this example does for single DBObject. Any idea please?

        if (field.isAnnotationPresent(DBRef.class) && field.isAnnotationPresent(CascadeSave.class)) {
            if (field.getType() == List.class || field.getType() == ArrayList.class) {
                List collection = (List) field.get(getSource());
                if (collection != null) {
                    Iterator iterator = collection.iterator();
                    while (iterator.hasNext()) {
                        final Object fieldValue = iterator.next();
                        if (fieldValue != null) {
                            final FieldCallback callback = new FieldCallback();
                            ReflectionUtils.doWithFields(fieldValue.getClass(), callback);
                            getMongoOperations().save(fieldValue);
                        }
                    }
                }
            } else {
                final Object fieldValue = field.get(getSource());
                if (fieldValue != null) {
                    final FieldCallback callback = new FieldCallback();
                    ReflectionUtils.doWithFields(fieldValue.getClass(), callback);
                    getMongoOperations().save(fieldValue);
                }
            }
        }

**Comment by d3minem** [comment]
After Debugging, I got this:

```
this = {CascadeCallback@11848} 
field = {Field@11630} "transient java.lang.Object[] java.util.ArrayList.elementData"
 clazz = {Class@337} "class java.util.ArrayList"
 slot = 4
 name = "elementData"
 type = {Class@597} "class [Ljava.lang.Object;"
 modifiers = 128
 signature = null
 genericInfo = null
 annotations = null
 fieldAccessor = null
 overrideFieldAccessor = {UnsafeObjectFieldAccessorImpl@11880} 
 root = {Field@11633} "transient java.lang.Object[] java.util.ArrayList.elementData"
 declaredAnnotations = {Collections$EmptyMap@11596}  size = 0
 override = true
 accessCheckCache = null
```

**Comment by d3minem** [comment]
Solved it! The problem was that example [baeldung](https://www.baeldung.com/cascading-with-dbref-and-lifecycle-events-in-spring-data-mongodb) also require to register or implement custom `UserCascadeSaveMongoEventListener` which don't need it. After removing the bean registration of above class, `CascadeCallback` class can see the @DBRef and @CascadeOnSave annotation of child class and the **if block** executed as per expectation. And everything was working perfectly fine the child collection saved properly.
