### ISSUE TITLE
Example FunctionalWebApplication throws IllegalArgumentException on localhost:9090

### ISSUE THREAD

**Issue by LoveraSantiago** [eugenp/tutorials#4331]
Hi. Good morning to all.

I'm starting do learn WebFlux.
I got here, coming from google search by webflux tutorials
I'm doing the example FunctionalWebApplication.java from package com.baeldung.functional.

After running this example I try on chrome and on postman to acces localhost:9090

I getting hit by this:
`11:48:12.212 [http-nio-9090-exec-6] ERROR org.springframework.web.server.adapter.HttpWebHandlerAdapter - Failed to handle request [POST http://localhost:9090/]
java.lang.IllegalArgumentException: Invalid contextPath: 'DefaultRequestPath[fullPath='[path='/']', contextPath='', pathWithinApplication='/']': must start with '/' and not end with '/'
	at org.springframework.http.server.DefaultRequestPath.validateContextPath(DefaultRequestPath.java:78)
	at org.springframework.http.server.DefaultRequestPath.initContextPath(DefaultRequestPath.java:57)
	at org.springframework.http.server.DefaultRequestPath.<init>(DefaultRequestPath.java:42)
	at org.springframework.http.server.RequestPath.parse(RequestPath.java:60)
	at org.springframework.http.server.reactive.AbstractServerHttpRequest.<init>(AbstractServerHttpRequest.java:74)
	at org.springframework.http.server.reactive.DefaultServerHttpRequestBuilder$DefaultServerHttpRequest.<init>(DefaultServerHttpRequestBuilder.java:166)
	at org.springframework.http.server.reactive.DefaultServerHttpRequestBuilder.build(DefaultServerHttpRequestBuilder.java:133)
	at org.springframework.web.server.DefaultServerWebExchangeBuilder.request(DefaultServerWebExchangeBuilder.java:59)
	at com.baeldung.functional.IndexRewriteFilter.filter(IndexRewriteFilter.java:19)
	at org.springframework.web.server.handler.DefaultWebFilterChain.lambda$filter$0(DefaultWebFilterChain.java:76)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3080)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:167)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3080)
	at org.springframework.http.server.reactive.ServletHttpHandlerAdapter.service(ServletHttpHandlerAdapter.java:180)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
11:48:12.212 [http-nio-9090-exec-6] DEBUG org.springframework.http.server.reactive.ServletHttpHandlerAdapter - Handling completed with success
`

I was expecting that IndexRewriteFilter.java on same package, would filter request on localhost:9090 to localhost:9090/test.

I`m assuming wrongs things?

**Comment by lor6** [comment]
Hey @LoveraSantiago There was an error in the IndexRewriteFilter - try to do a pull again and it should work. The context path was not configured correctly.

Fyi, the filter is set when building the HttpHandler in the start() method.

Cheers.
