### ISSUE TITLE
Having trouble with Spring Quartz

### ISSUE THREAD

**Issue by JohnReedLOL** [eugenp/tutorials#5276]
I tried to incorporate your code at https://github.com/eugenp/tutorials/tree/master/spring-quartz into my codebase and I'm running into a little issue.

Output: http://snippi.com/s/66bbz3q

Basically the important part is that on this line: 

`SchedulerFactoryBean schedulerFactory = new SchedulerFactoryBean(); // SpringQrtzScheduler.java Line 51 `

I am getting: 

```
Caused by: java.lang.NoClassDefFoundError: org/springframework/transaction/TransactionException
	at com.example.scheduler.basics.scheduler.SpringQrtzScheduler.scheduler(SpringQrtzScheduler.java:51)
	at com.example.scheduler.basics.scheduler.SpringQrtzScheduler$$EnhancerBySpringCGLIB$$10759ed7.CGLIB$scheduler$3(<generated>)
	at com.example.scheduler.basics.scheduler.SpringQrtzScheduler$$EnhancerBySpringCGLIB$$10759ed7$$FastClassBySpringCGLIB$$4c8906.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)
	at com.example.scheduler.basics.scheduler.SpringQrtzScheduler$$EnhancerBySpringCGLIB$$10759ed7.scheduler(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 26 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.transaction.TransactionException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 common frames omitted
        
```

Now I go on Google for a solution and I find:

https://www.mkyong.com/spring/java-lang-classnotfoundexception-org-springframework-transaction-transactionexception/

https://stackoverflow.com/questions/36277307/spring-noclassdeffounderror

So I go into my pom.xml and add: 

```
   <dependency>
	<groupId>org.springframework</groupId>
	<artifactId>spring-tx</artifactId>
	<version>3.1.2.RELEASE</version>
   </dependency>
```

Now I recompile and re-run and I get this: https://gist.github.com/JohnReedLOL/ce845e43504b4f171c056c230bf1137f

Also, my pom.xml looks like this: https://gist.github.com/JohnReedLOL/3fd8c15af3cedcabcfb2c329b44761b3

**Comment by lor6** [comment]
Hey @JohnReedLOL  You're using Spring Boot 2 with very a very old version of spring-tx. If you want a jdbc job store with transaction support in a Spring Boot application, I suggest adding the spring-boot-starter-jdbc dependency which will bring in the correct version of spring-tx.

**Comment by eugenp** [comment]
Anything left to do here?
If so - feel free to reopen it, @JohnReedLOL . 

Cheers, 
Eugen.
