### ISSUE TITLE
Unable to build a fat jar . Caused by: java.awt.HeadlessExceoption: null

### ISSUE THREAD

**Issue by nobleson** [eugenp/tutorials#6201]
Sir, 
I have followed the tutorials from your site [https://www.baeldung.com/executable-jar-with-maven](here) and [https://www.baeldung.com/deployable-fat-jar-spring-boot](here).
In my application, i have my views in html and would like to serve them via a web server.
I have a created a spring-boot application to enable me embed tomcat, which i did.
I also  want to render the views from a javafx webview instead of using  a conventional browser.
I therefore integrate Swing-Javafx API in the project.
When i run the application, the tomcat get started and the GUI is initialized, and with the remote url served to the webview engine, i got the view displayed inside my swing frame.
My problem is  when i perform: mvnw clean installed i got the headless error.
Some answers suggest that i should set headless=false but i does not work.

`        SpringApplicationBuilder builder = new SpringApplicationBuilder(JambmockCbtApplication.class);
        builder.headless(false);
        ConfigurableApplicationContext ctx = builder.run(args);
`
The maven plugin:
`		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
`
The exception:
`Caused by: java.awt.HeadlessException: null
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204) ~[na:1.8.0_111]
        at java.awt.Window.<init>(Window.java:536) ~[na:1.8.0_111]
        at java.awt.Frame.<init>(Frame.java:420) ~[na:1.8.0_111]
        at java.awt.Frame.<init>(Frame.java:385) ~[na:1.8.0_111]
        at javax.swing.JFrame.<init>(JFrame.java:189) ~[na:1.8.0_111]
        at com.mutualinks.jambmock.jambmockcbt.TestUI.<init>(TestUI.java:28) ~[classes/:na]
        at com.mutualinks.jambmock.jambmockcbt.JambmockCbtApplication.initUI(JambmockCbtApplication.java:17) ~[classes/:na]
        at com.mutualinks.jambmock.jambmockcbt.JambmockCbtApplication.<init>(JambmockCbtApplication.java:13) ~[classes/:na]
        at com.mutualinks.jambmock.jambmockcbt.JambmockCbtApplication$$EnhancerBySpringCGLIB$$1b04b30b.<init>(<generated>) ~[classes/:na]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_111]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_111]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_111]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_111]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172) ~[spring-beans-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        ... 45 common frames omitted

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 14.071 s <<< FAILURE! - in com.mutualinks.jambmock.jambmockcbt.JambmockCbtApplicationTests
[ERROR] contextLoads(com.mutualinks.jambmock.jambmockcbt.JambmockCbtApplicationTests)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jambmockCbtApplication': Instantiation of bean failed; nested exception is org.sp
ringframework.beans.BeanInstantiationException: Failed to instantiate [com.mutualinks.jambmock.jambmockcbt.JambmockCbtApplication$$EnhancerBySpringCGLIB$$1b04b30b]: Constructor thr
ew exception; nested exception is java.awt.HeadlessException
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.mutualinks.jambmock.jambmockcbt.JambmockCbtApplication$$EnhancerBySpringCGLIB$$1b04b30b]
: Constructor threw exception; nested exception is java.awt.HeadlessException
Caused by: java.awt.HeadlessException

`
Please i need help, thanks.

**Comment by maibin** [comment]
Hey @nobleson. I believe you have some custom problem, rather than an issue with our code. Could you please create a stackoverflow question and then send the link to us over an email? This way we would be able to help you with your implementation.
