### ISSUE TITLE
Wicket cafe example throwing exception

### ISSUE THREAD

**Issue by jwenting** [eugenp/tutorials#6253]
Running in Tomcat 9, I get the following exception trying to load http://localhost:8080/wicket-1.0-SNAPSHOT/examples/cafes

08:22:05.000 [http-nio-8080-exec-1] WARN  RequestCycleExtra - ********************************
08:22:05.005 [http-nio-8080-exec-1] WARN  RequestCycleExtra - Handling the following exception
org.apache.wicket.WicketRuntimeException: Exception in rendering component: [Component id = address]
        at org.apache.wicket.Component.internalRenderComponent(Component.java:2637)
        at org.apache.wicket.markup.html.WebComponent.onRender(WebComponent.java:60)
        at org.apache.wicket.Component.internalRender(Component.java:2413)
        at org.apache.wicket.Component.render(Component.java:2341)
        at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1526)
        at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1729)
        at org.apache.wicket.Page.onRender(Page.java:879)
        at org.apache.wicket.markup.html.WebPage.onRender(WebPage.java:141)
        at org.apache.wicket.Component.internalRender(Component.java:2413)
        at org.apache.wicket.Component.render(Component.java:2341)
        at org.apache.wicket.Page.renderPage(Page.java:1018)
        at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:124)
        at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:236)
        at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:175)
        at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:895)
        at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
        at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265)
        at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222)
        at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293)
        at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261)
        at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:203)
        at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:284)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: An error occurred while getting the model object for Component: [Component id = address, page = com.baeldung.wicket.examples.cafeaddress.CafeAddress, path = 0:address.Label, isVisible = true, isVersioned = true, markup = [markup = file:/D:/tools/apache-tomcat-9.0.12/webapps/wicket-1.0-SNAPSHOT/WEB-INF/classes/com/baeldung/wicket/examples/cafeaddress/CafeAddress.html
<span wicket:id="address">address</span>, index = 0, current =  '<span wicket:id="address">' (line 0, column 0)]]
        at org.apache.wicket.Component.getDefaultModelObject(Component.java:1664)
        at org.apache.wicket.Component.getDefaultModelObjectAsString(Component.java:1687)
        at org.apache.wicket.markup.html.basic.Label.onComponentTagBody(Label.java:115)
        at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:70)
        at org.apache.wicket.Component.internalRenderComponent(Component.java:2613)
        ... 40 common frames omitted
Caused by: org.apache.wicket.WicketRuntimeException: Property could not be resolved for class: class com.baeldung.wicket.examples.cafeaddress.CafeAddress$Address expression: address
        at org.apache.wicket.core.util.lang.PropertyResolver.getGetAndSet(PropertyResolver.java:393)
        at org.apache.wicket.core.util.lang.PropertyResolver.getObjectWithGetAndSet(PropertyResolver.java:355)
        at org.apache.wicket.core.util.lang.PropertyResolver.getObjectWithGetAndSet(PropertyResolver.java:261)
        at org.apache.wicket.core.util.lang.PropertyResolver.getValue(PropertyResolver.java:111)
        at org.apache.wicket.model.AbstractPropertyModel.getObject(AbstractPropertyModel.java:86)
        at org.apache.wicket.Component.getDefaultModelObject(Component.java:1659)
        ... 44 common frames omitted
08:22:05.006 [http-nio-8080-exec-1] WARN  RequestCycleExtra - ********************************
08:22:05.009 [http-nio-8080-exec-1] ERROR o.a.wicket.DefaultExceptionMapper - Unexpected error occurred
org.apache.wicket.WicketRuntimeException: Exception in rendering component: [Component id = address]
        at org.apache.wicket.Component.internalRenderComponent(Component.java:2637)
        at org.apache.wicket.markup.html.WebComponent.onRender(WebComponent.java:60)
        at org.apache.wicket.Component.internalRender(Component.java:2413)
        at org.apache.wicket.Component.render(Component.java:2341)
        at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1526)
        at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1729)
        at org.apache.wicket.Page.onRender(Page.java:879)
        at org.apache.wicket.markup.html.WebPage.onRender(WebPage.java:141)
        at org.apache.wicket.Component.internalRender(Component.java:2413)
        at org.apache.wicket.Component.render(Component.java:2341)
        at org.apache.wicket.Page.renderPage(Page.java:1018)
        at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:124)
        at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:236)
        at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:175)
        at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:895)
        at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
        at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265)
        at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222)
        at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293)
        at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261)
        at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:203)
        at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:284)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: An error occurred while getting the model object for Component: [Component id = address, page = com.baeldung.wicket.examples.cafeaddress.CafeAddress, path = 0:address.Label, isVisible = true, isVersioned = true, markup = [markup = file:/D:/tools/apache-tomcat-9.0.12/webapps/wicket-1.0-SNAPSHOT/WEB-INF/classes/com/baeldung/wicket/examples/cafeaddress/CafeAddress.html
<span wicket:id="address">address</span>, index = 0, current =  '<span wicket:id="address">' (line 0, column 0)]]
        at org.apache.wicket.Component.getDefaultModelObject(Component.java:1664)
        at org.apache.wicket.Component.getDefaultModelObjectAsString(Component.java:1687)
        at org.apache.wicket.markup.html.basic.Label.onComponentTagBody(Label.java:115)
        at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:70)
        at org.apache.wicket.Component.internalRenderComponent(Component.java:2613)
        ... 40 common frames omitted
Caused by: org.apache.wicket.WicketRuntimeException: Property could not be resolved for class: class com.baeldung.wicket.examples.cafeaddress.CafeAddress$Address expression: address
        at org.apache.wicket.core.util.lang.PropertyResolver.getGetAndSet(PropertyResolver.java:393)
        at org.apache.wicket.core.util.lang.PropertyResolver.getObjectWithGetAndSet(PropertyResolver.java:355)
        at org.apache.wicket.core.util.lang.PropertyResolver.getObjectWithGetAndSet(PropertyResolver.java:261)
        at org.apache.wicket.core.util.lang.PropertyResolver.getValue(PropertyResolver.java:111)
        at org.apache.wicket.model.AbstractPropertyModel.getObject(AbstractPropertyModel.java:86)
        at org.apache.wicket.Component.getDefaultModelObject(Component.java:1659)
        ... 44 common frames omitted

**Comment by maibin** [comment]
@jwenting could you please let us know which article you are referring to?

**Comment by jwenting** [comment]
https://www.baeldung.com/intro-to-the-wicket-framework

This one, but got that error just trying to run the examples after downloading them from Github.
