### ISSUE TITLE
Java Web Start Issue When Hosted in IIS

### ISSUE THREAD

**Issue by DarshanKsheerasagar** [eugenp/tutorials#6328]
jsw example i hosted in IIS but its showing me the Error as Hello Class . Attachment file with hosted files

**Comment by DarshanKsheerasagar** [comment]
Please attached image i found Class Not found exception like below 


java.lang.ClassNotFoundException: com.example.Hello
	at java.net.URLClassLoader.findClass(Unknown Source)
	at com.sun.jnlp.JNLPClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.sun.jnlp.JNLPClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.sun.javaws.Launcher.doLaunchApp(Unknown Source)
	at com.sun.javaws.Launcher.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by DarshanKsheerasagar** [comment]
@TomaszLinkowski reply me

**Comment by eric-martin** [comment]
@DarshanKsheerasagar Can you please list the steps to reproduce this problem?
