### ISSUE TITLE
Null Pointer when saving data into cassandra

### ISSUE THREAD

**Issue by johnpalantir** [eugenp/tutorials#8274]
Getting null pointer at https://github.com/eugenp/tutorials/blob/master/apache-spark/src/main/java/com/baeldung/data/pipeline/WordCountingApp.java 

 wordCounts.foreachRDD(javaRdd -> {
            Map<String, Integer> wordCountMap = javaRdd.collectAsMap();
            for (String key : wordCountMap.keySet()) {
                List<Word> wordList = Arrays.asList(new Word(key, wordCountMap.get(key)));
                JavaRDD<Word> rdd = streamingContext.sparkContext()
                    .parallelize(wordList);
                javaFunctions(rdd).writerBuilder("vocabulary", "words", mapToRow(Word.class))
                    .saveToCassandra();
            }
        });

**Comment by johnpalantir** [comment]
ref: https://www.baeldung.com/kafka-spark-data-pipeline

**Comment by johnpalantir** [comment]
- Error running job streaming job 1575065360000 ms.0
java.lang.NullPointerException: null
	at com.datastax.driver.core.Cluster$Manager.close(Cluster.java:1627)
	at com.datastax.driver.core.Cluster$Manager.access$200(Cluster.java:1318)
	at com.datastax.driver.core.Cluster.closeAsync(Cluster.java:566)
	at com.datastax.driver.core.Cluster.close(Cluster.java:578)
	at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:167)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$8.apply(CassandraConnector.scala:154)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$8.apply(CassandraConnector.scala:154)
	at com.datastax.spark.connector.cql.RefCountedCache.createNewValueAndKeys(RefCountedCache.scala:32)
	at com.datastax.spark.connector.cql.RefCountedCache.syncAcquire(RefCountedCache.scala:69)
	at com.datastax.spark.connector.cql.RefCountedCache.acquire(RefCountedCache.scala:57)
	at com.datastax.spark.connector.cql.CassandraConnector.openSession(CassandraConnector.scala:79)
	at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:111)
	at com.datastax.spark.connector.cql.CassandraConnector.withClusterDo(CassandraConnector.scala:122)
	at com.datastax.spark.connector.cql.Schema$.fromCassandra(Schema.scala:332)
	at com.datastax.spark.connector.cql.Schema$.tableFromCassandra(Schema.scala:352)
	at com.datastax.spark.connector.writer.TableWriter$.apply(TableWriter.scala:383)
	at com.datastax.spark.connector.RDDFunctions.saveToCassandra(RDDFunctions.scala:35)
	at com.datastax.spark.connector.japi.RDDJavaFunctions.saveToCassandra(RDDJavaFunctions.java:61)
Exception in thread "main" 	at com.datastax.spark.connector.japi.RDDAndDStreamCommonJavaFunctions$WriterBuilder.saveToCassandra(RDDAndDStreamCommonJavaFunctions.java:486)
	at com.palantir.KafkaSparkCassandraStreaming.streams.SparkStreamKafkaCassandApp.lambda$main$b0eecefb$1(SparkStreamKafkaCassandApp.java:88)
	at org.apache.spark.streaming.api.java.JavaDStreamLike$$anonfun$foreachRDD$1.apply(JavaDStreamLike.scala:272)
	at org.apache.spark.streaming.api.java.JavaDStreamLike$$anonfun$foreachRDD$1.apply(JavaDStreamLike.scala:272)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:628)
java.lang.NullPointerException
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:628)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ForEachDStream.scala:51)
	at com.datastax.driver.core.Cluster$Manager.close(Cluster.java:1627)
	at com.datastax.driver.core.Cluster$Manager.access$200(Cluster.java:1318)	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51)

	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.DStream.createRDDWithLocalProperties(DStream.scala:416)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply$mcV$sp(ForEachDStream.scala:50)
	at com.datastax.driver.core.Cluster.closeAsync(Cluster.java:566)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50)
	at com.datastax.driver.core.Cluster.close(Cluster.java:578)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50)

**Comment by maibin** [comment]
@johnpalantir we did check it on our side and everything seems fine. Since there are a lot of local configuration frameworks involved, could you please let us know how do you setup you Spark and Cassandra?
